class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)

    if @user.save
      # :location option is setting the HTTP Location Header
      # :status is for overwriting the HTTP response generated by rails
      render json: @user, status: :created, location: @user
    else
      render json: @user.errors, status: :unprocessable_entity
    end
  end

  def login
    user = User.find_by(email: params[:email])

    if user && user.authenticate(params[:password])
      render json: {"token" => user.token}
    else
      # The head method can be used to send responses with only headers to the browser.
      head :unauthorized
    end
  end

  def logout
    head :ok
  end

  private

    def user_params
      params.require(:user).permit(:username, :email, :password, :password_confirmation, :token, :status, :image)
    end

    def get_token
    end
end